[build]
  # No build command needed for static site
  publish = "."

[build.environment]
  # No environment variables needed

[[headers]]
  # Apply security headers to all pages
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  # Cache static assets
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  # Cache HTML with shorter duration
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Redirect rules (if needed)
[[redirects]]
  from = "/home"
  to = "/"
  status = 301

# Custom 404 page (optional)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 